---
- name: Get the filename of the latest MySQL APT repo package
  shell: >
    curl -s https://dev.mysql.com/downloads/repo/apt/ |
    grep -oP 'mysql-apt-config_\d+\.\d+\.\d+-\d+_all.deb' |
    head -n 1
  args:
    warn: false
  register: mysql_repo_filename
  changed_when: false

- name: Set .deb package file name
  set_fact:
    mysql_repo_url: "{{ mysql_repo_filename.stdout }}"

- name: Download MySQL APT config file
  get_url:
    url: https://dev.mysql.com/get/{{ mysql_repo_url }}
    dest: /tmp/{{ mysql_repo_url }}
    headers:
      User-Agent: "Mozilla/5.0 (compatible; Ansible)"

- name: Add the mysql apt config repo
  apt:
    deb: /tmp/{{ mysql_repo_url }}

- name: Install mysql-apt-config
  ansible.builtin.apt:
    name: mysql-apt-config
    update_cache: yes

- name: Install mysql-client
  ansible.builtin.apt:
    name: mysql-client

- name: Install mysql-shell
  ansible.builtin.apt:
    name: mysql-shell

- name: Install percona-toolkit
  ansible.builtin.apt:
    name: percona-toolkit

- name: Create a directory for MySQL Random Data Loader
  file:
    path: /usr/local/bin/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download MySQL Random Data Loader tarball
  get_url:
    url: https://github.com/Percona-Lab/mysql_random_data_load/releases/download/v0.1.12/mysql_random_data_load_0.1.12_Linux_x86_64.tar.gz
    dest: /tmp/mysql_random_data_load_0.1.12_Linux_x86_64.tar.gz

- name: Extract MySQL Random Data Loader tarball
  ansible.builtin.unarchive:
    src: /tmp/mysql_random_data_load_0.1.12_Linux_x86_64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/mysql_random_data_load_0.1.12_Linux_x86_64/

- name: Make MySQL Random Data Loader executable
  file:
    path: /usr/local/bin/mysql_random_data_load
    mode: '+x'
    owner: root
    group: root

- name: Download sakila database
  get_url: 
    url: https://downloads.mysql.com/docs/sakila-db.tar.gz
    dest: /tmp
    headers:
      User-Agent: "Mozilla/5.0 (compatible; Ansible)"
    

- name: Extract sakila database
  unarchive: 
    src: /tmp/sakila-db.tar.gz
    dest: /home/vagrant 
    remote_src: yes

