---
- name: Install python and docker
  hosts: all
  become: true

  tasks:

    - name: update cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install python
      apt:
        name: python3
        state: latest
        update_cache: true
        autoclean: yes

    - name: Install pip
      apt:
        name: python3-pip
        state: latest

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest

    - name: Install required system packages
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
        state: latest

    - name: Create a keyrings if it does not exist
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add the Docker repository
      apt_repository:
        repo: 'deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker