---
- name: Install python and docker
  hosts: all
  become: true
  roles: 
    - role: python_install
      tags: python_install
    - role: common_requirements
      tags: common_requirements
    - role: docker_install
      tags: docker_install
