---
- name: Install python and docker
  hosts: all
  become: true
  roles: 
    - role: python_install
      tags: python_install
    - role: common_requirements
      tags: common_requirements
    - role: docker_install
      tags: docker_install
    - role: git_config
      tags: git_config
    - role: aws_cli_install
      tags: aws_cli_install
    - role: bashrc_config
      tags: bashrc_config
    - role: terraform_install
      tags: terraform_install
    - role: mysql_tools_install
      tags: mysql_tools_install
